### ISSUE TITLE
Frequently out of sync with actual state?

### ISSUE THREAD

**Issue by nneul** [yktoo/indicator-sound-switcher#57] opened 2017-08-24 20:05 UTC
I've been using 2.1.1 on UB 16.04 LTS x64 - it's the best tool for the job I've found.

It does seem to have a couple issues though.

1) It appears that the state of the menu frequently doesn't match up with the actual input/output selections. Choosing an item does switch to that item though.

2) This one is a bit more inconsistent - it seems I frequently have to change the selection TWICE for it to take effect. I suspect that there may be some connection to whatever is causing (1) above. 

Any suggestions on the above or requested diagnostics that might help narrow down the problem?

**Comment by nneul** [comment] 2017-08-24 20:07
Just saw #42 - I think my 2. above may be a duplicate of that.

**Comment by yktoo** [comment] 2019-06-21 14:00
It all looks indeed as a duplicate of #42. Try disabling `restore_device` and see if it helps. Closing for now.

**Closed by yktoo** 2019-06-21 14:00 UTC
Labels: duplicate
