### ISSUE TITLE
Does not recognize my HDMI output

### ISSUE THREAD

**Issue by gitfineon** [yktoo/indicator-sound-switcher#23] opened 2016-07-11 09:42 UTC
![selection_056](https://cloud.githubusercontent.com/assets/11716650/16726157/0a743abc-475b-11e6-8f63-e8c2bef656fe.png)

I'm still using my old Dell Vostro 3500, because it works perfect with Ubuntu for years. 
Switching "Audio Output" through "System settings -> Audio -> Output" ist really anoying and I truly miss the feature to set automatic rules, e.g. on connecting HDMI, automatically switch audio to HDMI.

Your indicator is a good step forward, but I can't use it with my hardware, because HDMI Audio is not recognized by the indicator applet.

My Hardware: 1st Gen Core i5 with onboard graphics
Still using Ubuntu 15.10

**Comment by Lazza** [comment] 2016-07-20 13:19
I am encountering the opposite problem... only HDMI is recognized. :grin: I am using a Samsung Series 5 ultrabook.

**Comment by repsa** [comment] 2016-08-07 13:35
> I am encountering the opposite problem... only HDMI is recognized. :grin: I am using a Samsung Series 5 ultrabook.

The same issue

Lenovo ThinckPad SL500
Ubuntu 14.04, 16.04

**Comment by repsa** [comment] 2016-08-07 14:08
> I am encountering the opposite problem... only HDMI is recognized. :grin: I am using a Samsung Series 5 ultrabook.

Как можно подебажить инициализацию списка устройств вывода аудио?

**Comment by repsa** [comment] 2016-08-07 19:21
@gitfineon , @Lazza , it seems i find solution! 
It's PulseAudio issue, and I got success with this [solution](https://wiki.archlinux.org/index.php/PulseAudio/Examples#Simultaneous_HDMI_and_analog_output)

**Comment by Lazza** [comment] 2016-08-08 10:46
Thanks for pointing it out. I will have a look.

**Comment by yktoo** [comment] 2016-09-25 15:32
Duplicate of #3

**Closed by yktoo** 2016-09-25 15:32 UTC
