### ISSUE TITLE
[BUG] Switch does not show current selected output on Ubuntu 20.04

### ISSUE THREAD

**Issue by laryro** [yktoo/indicator-sound-switcher#94] opened 2020-10-19 21:57 UTC
**Describe the bug**

**To Reproduce**
1. Connect Bluetooth headphone
2. Open the switcher menu
3. Try to change the output

**Expected behavior**
On Ubuntu 20.04 LTS, the indicator does not work when switching between speakers and Bluetooth headphones. When you click the options on the switcher, Ubuntu does not change the current output and the sound is not reproduced, nor on headphones, nor on speaker.

**Screenshots**
![Screenshot from 2020-10-19 18-48-45](https://user-images.githubusercontent.com/2932468/96515893-7da16900-123c-11eb-911d-437da3ad6fe7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Desktop environment: GNOME 3.36.3
 - Sound Switcher Indicator version: 2.3.4

**Indicator log:**
```bash
# OUTPUT WHEN THE OUTPUT IS SELECTED VIA UBUNTU SETTINGS (SPEAKERS)

DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 5)
DEBUG      * Source[5] updated: `alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__source`, card 0
DEBUG        * Activated source port `[In] Headset`
DEBUG    .do_context_subscribe(facility: 3, kind: 32, index: 22)
DEBUG      - Source output[22] removed: `Peak detect`
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 4)
DEBUG      * Sink[4] updated: `alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink`, card 0
DEBUG        * Activated sink port `[Out] Speaker`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 4)
DEBUG    .do_context_subscribe(facility: 3, kind: 0, index: 23)
DEBUG      + Source output[23] added: `Peak detect`
DEBUG    .do_context_subscribe(facility: 7, kind: 16, index: 4294967295)
DEBUG    * Activated sink: `alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink`
DEBUG    * Activated source: `alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source`
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 60)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `bluez_sink.74_45_CE_31_59_1E.a2dp_sink`, card 1
DEBUG        * Activated sink port `headset-output`
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 91)
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 5)
DEBUG      * Source[5] updated: `alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__source`, card 0
DEBUG        * Activated source port `[In] Headset`
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `bluez_sink.74_45_CE_31_59_1E.a2dp_sink`, card 1
DEBUG        * Activated sink port `headset-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 9, kind: 16, index: 1)
DEBUG      * Card[1] updated
DEBUG        * Activated profile: `a2dp_sink` (`High Fidelity Playback (A2DP Sink)`)


# OUTPUT WHEN HEADPHONE IS SELECTED VIA UBUNTU SETTINGS

DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 4)
DEBUG    .do_context_subscribe(facility: 3, kind: 32, index: 23)
DEBUG      - Source output[23] removed: `Peak detect`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 5)
DEBUG      * Source[5] updated: `alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__source`, card 0
DEBUG        * Activated source port `[In] Headset`
DEBUG    .do_context_subscribe(facility: 3, kind: 0, index: 24)
DEBUG      + Source output[24] added: `Peak detect`
DEBUG    .do_context_subscribe(facility: 7, kind: 16, index: 4294967295)
DEBUG    * Activated sink: `bluez_sink.74_45_CE_31_59_1E.a2dp_sink`
DEBUG    * Activated source: `alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source`
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `bluez_sink.74_45_CE_31_59_1E.a2dp_sink`, card 1
DEBUG        * Activated sink port `headset-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 60)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 4)
DEBUG      * Sink[4] updated: `alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink`, card 0
DEBUG        * Activated sink port `[Out] Speaker`
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 91)
DEBUG    .do_context_subscribe(facility: 9, kind: 16, index: 1)
DEBUG      * Card[1] updated
DEBUG        * Activated profile: `a2dp_sink` (`High Fidelity Playback (A2DP Sink)`)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 4)
DEBUG      * Sink[4] updated: `alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink`, card 0
DEBUG        * Activated sink port `[Out] Speaker`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 4)
```

**Additional context**
I've recently changed my machine and now it's using Ubuntu 20.04. With the same headphones, on Ubuntu 18.04, it used to work well...

**Comment by yktoo** [comment] 2022-05-13 17:20
Looks like duplicate of #107. Can you please check if it's resolved in 2.3.8?

**Closed by yktoo** 2022-05-13 17:20 UTC
Labels: bug, duplicate
