### ISSUE TITLE
Buggy icons

### ISSUE THREAD

**Issue by leobasilio** [yktoo/indicator-sound-switcher#87] opened 2020-05-26 01:33 UTC
There's something wrong with the new icons added by 655479da. I'm running MATE 1.20.1 and here's how I see them:

![Icon1](https://user-images.githubusercontent.com/16745138/82851652-cb58b600-9ed6-11ea-8896-26c5fcf7a0a9.png)

The weird thing is that it looks perfect on Inkscape. I tried saving it as plain svg, but it didn't have any effect.

![Icon2](https://user-images.githubusercontent.com/16745138/82851675-e7f4ee00-9ed6-11ea-8fb5-8be838c89a6c.png)

**Comment by yktoo** [comment] 2020-05-26 07:52
Weird indeed. I checked both icons with the [SVG validator by W3c](https://validator.w3.org/) and the [SVG sanitizer](http://svg.enshrined.co.uk/), both were happy with the input. The only issue the W3C validator found was the SVG version number that should better be removed.

In Ubuntu they also work perfectly. Does MATE perhaps have known issues with SVG rendering?

**Comment by phdzor** [comment] 2020-05-26 08:54
After update today icon has weird shape + since its black you cant even see it.
![Screenshot_20200526_104951](https://user-images.githubusercontent.com/51232573/82880505-cfb8b980-9f3e-11ea-9e8c-905bd104ef64.png)

Im running Kubuntu 20.04

**Comment by yktoo** [comment] 2020-05-26 11:57
> ![Screenshot_20200526_104951](https://user-images.githubusercontent.com/51232573/82880505-cfb8b980-9f3e-11ea-9e8c-905bd104ef64.png)
> 
> Im running Kubuntu 20.04

Okay, this one looks like symbolic icons are only supported by Gnome, which changes the icon's colour depending on the theme

**Comment by yousefsaif** [comment] 2020-05-26 14:34
Similar issue on Ubuntu 18.04 LTS (Gnome)

![Screenshot from 2020-05-26 15-29-17](https://user-images.githubusercontent.com/32868773/82913524-51700d80-9f66-11ea-9f28-a9a5651f9500.png)

**Comment by yktoo** [comment] 2020-05-26 15:55
Okay I've been able to reproduce this crazy rendering on Xubuntu 18.04. Will push an update soon.

**Comment by yktoo** [comment] 2020-05-26 16:42
The garbled appearance was clearly caused by SVGO I used to optimise the icons. This has been undone.

**Comment by leobasilio** [comment] 2020-05-26 17:55
I have downloaded the new files and it looks fine now.

![Captura de tela em 2020-05-26 14-01-40](https://user-images.githubusercontent.com/16745138/82929087-81fd7a80-9f59-11ea-8d36-ecc8629ab08f.png)

The color doesn't match, but that's likely due to my custom icons theme. However, it seems that the [key color](https://askubuntu.com/a/154846) should be #bebebe and not black. This might affect other people.

**Comment by yktoo** [comment] 2020-05-26 19:18
Resolved in 2.3.3.

I will look into fixing the color, I've also opened a [question on SO](https://unix.stackexchange.com/questions/589064/symbolic-icon-for-various-des).

**Closed by yktoo** 2020-05-26 19:18 UTC
Labels: resolved in dev

**Comment by yktoo** [comment] 2020-06-02 17:21
For those interested which SVGO's option exactly breaks the SVGs, its the `convertPathData` plugin. The result looks fine when used as:

```bash
svgo --disable=convertPathData ...
```
