### ISSUE TITLE
[BUG] Software icon don't appear in system tray and doesn't works fine

### ISSUE THREAD

**Issue by NewMaxT** [yktoo/indicator-sound-switcher#110] opened 2021-08-15 17:11 UTC
Hello there !
**Describe the bug**
When I start the software it doesn't appear in system trays (Maybe because of the desktop environnment)

**To Reproduce**

Open a terminal on ElementaryOS 6
Write 'sudo indicator-sound-switcher'
The terminal outputs 'WARNING Context failed' few times and just after quitting 'Couldn't connect to pulseaudio server'

When trying without sudo you'll not have any outputs and the app not appear in the system tray or else
So it seems that sudo mode isn't great for this software but it would work without.

**Desktop (please complete the following information):**
 - OS: ElementaryOS 6 (Ubuntu 20 lts based system)
 - Linux Kernel is Linux 5.11.0-25-generic
 - The desktop environment is [Pantheon](https://wiki.archlinux.org/title/Pantheon)
 - Sound Switcher Indicator version is 2.3.6

**Indicator log:**

```bash
newmax@censured:~/Applications/gtk-4.3.2$ indicator-sound-switcher -vv
INFO     Starting indicator application
INFO     Configuration file /home/newmax/.config/indicator-sound-switcher.json not found, falling back to defaults
DEBUG    KeyboardManager.bind_keys()
DEBUG    .menu_append_item(): appending item `Entrés`
DEBUG    .menu_append_item(): appending separator
DEBUG    .menu_append_item(): appending item `Sorties`
DEBUG    .menu_append_item(): appending separator
DEBUG    .menu_append_item(): appending item `_Actualiser`
DEBUG    .menu_append_item(): appending item `_Préférences…`
DEBUG    .menu_append_item(): appending item `À _propos`
DEBUG    .menu_append_item(): appending item `_Quitter`
DEBUG    Trying to connect to PulseAudio daemon, attempt #1
INFO     Context connected
DEBUG      + Card[0] added: `alsa_card.usb-0c76_USB_PnP_Audio_Device-00`, driver: `module-alsa-card.c`
DEBUG        + Card profile added: `input:mono-fallback` (`Entrée Mono`), 0 sinks, 1 sources, priority: 1
DEBUG        + Card profile added: `input:multichannel-input` (`Entrée Multicanal`), 0 sinks, 1 sources, priority: 1
DEBUG        + Card profile added: `output:analog-stereo` (`Sortie Stéréo analogique`), 1 sinks, 0 sources, priority: 6500
DEBUG        + Card profile added: `output:analog-stereo+input:mono-fallback` (`Sortie Stéréo analogique + Entrée Mono`), 1 sinks, 1 sources, priority: 6501 -- Active
DEBUG        + Card profile added: `output:analog-stereo+input:multichannel-input` (`Sortie Stéréo analogique + Entrée Multicanal`), 1 sinks, 1 sources, priority: 6501
DEBUG        + Card profile added: `output:iec958-stereo` (`Sortie Stéréo numérique (IEC958)`), 1 sinks, 0 sources, priority: 5500
DEBUG        + Card profile added: `output:iec958-stereo+input:mono-fallback` (`Sortie Stéréo numérique (IEC958) + Entrée Mono`), 1 sinks, 1 sources, priority: 5501
DEBUG        + Card profile added: `output:iec958-stereo+input:multichannel-input` (`Sortie Stéréo numérique (IEC958) + Entrée Multicanal`), 1 sinks, 1 sources, priority: 5501
DEBUG        + Card profile added: `off` (`Éteint`), 0 sinks, 0 sources, priority: 0
DEBUG        + Card port added: `analog-input-mic` (`Microphone`); priority: 8700; direction: 2; available: Yes
DEBUG          . Supported profile: `input:mono-fallback`
DEBUG          . Supported profile: `output:analog-stereo+input:mono-fallback`
DEBUG          . Supported profile: `output:iec958-stereo+input:mono-fallback`
DEBUG        + Card port added: `multichannel-input` (`Entrée multicanal`); priority: 0; direction: 2; available: Yes
DEBUG          . Supported profile: `input:multichannel-input`
DEBUG          . Supported profile: `output:analog-stereo+input:multichannel-input`
DEBUG          . Supported profile: `output:iec958-stereo+input:multichannel-input`
DEBUG        + Card port added: `analog-output-speaker` (`Haut-parleurs`); priority: 10000; direction: 1; available: Yes
DEBUG          . Supported profile: `output:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:mono-fallback`
DEBUG          . Supported profile: `output:analog-stereo+input:multichannel-input`
DEBUG        + Card port added: `iec958-stereo-output` (`Sortie numérique (S/PDIF)`); priority: 0; direction: 1; available: Yes
DEBUG          . Supported profile: `output:iec958-stereo`
DEBUG          . Supported profile: `output:iec958-stereo+input:mono-fallback`
DEBUG          . Supported profile: `output:iec958-stereo+input:multichannel-input`
DEBUG    .menu_insert_ordered_item(): inserting item `    USB PnP Audio Device ‣ Microphone` at index 1
DEBUG    .menu_insert_ordered_item(): inserting item `    USB PnP Audio Device ‣ Entrée multicanal` at index 1
DEBUG    .menu_insert_ordered_item(): inserting item `    USB PnP Audio Device ‣ Haut-parleurs` at index 5
DEBUG    .menu_insert_ordered_item(): inserting item `    USB PnP Audio Device ‣ Sortie numérique (S/PDIF)` at index 6
DEBUG      + Card[1] added: `alsa_card.pci-0000_00_1f.3`, driver: `module-alsa-card.c`
DEBUG        + Card profile added: `input:analog-stereo` (`Entrée Stéréo analogique`), 0 sinks, 1 sources, priority: 32833
DEBUG        + Card profile added: `output:analog-stereo` (`Sortie Stéréo analogique`), 1 sinks, 0 sources, priority: 39268
DEBUG        + Card profile added: `output:analog-stereo+input:analog-stereo` (`Duplex stéréo analogique`), 1 sinks, 1 sources, priority: 39333 -- Active
DEBUG        + Card profile added: `output:hdmi-stereo` (`Sortie Digital Stereo (HDMI)`), 1 sinks, 0 sources, priority: 5900
DEBUG        + Card profile added: `output:hdmi-stereo+input:analog-stereo` (`Sortie Digital Stereo (HDMI) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 5965
DEBUG        + Card profile added: `output:hdmi-surround` (`Sortie Digital Surround 5.1 (HDMI)`), 1 sinks, 0 sources, priority: 800
DEBUG        + Card profile added: `output:hdmi-surround+input:analog-stereo` (`Sortie Digital Surround 5.1 (HDMI) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 865
DEBUG        + Card profile added: `output:hdmi-surround71` (`Sortie Digital Surround 7.1 (HDMI)`), 1 sinks, 0 sources, priority: 800
DEBUG        + Card profile added: `output:hdmi-surround71+input:analog-stereo` (`Sortie Digital Surround 7.1 (HDMI) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 865
DEBUG        + Card profile added: `output:hdmi-stereo-extra1` (`Sortie Digital Stereo (HDMI 2)`), 1 sinks, 0 sources, priority: 38468
DEBUG        + Card profile added: `output:hdmi-stereo-extra1+input:analog-stereo` (`Sortie Digital Stereo (HDMI 2) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 38533
DEBUG        + Card profile added: `output:hdmi-stereo-extra2` (`Sortie Digital Stereo (HDMI 3)`), 1 sinks, 0 sources, priority: 5700
DEBUG        + Card profile added: `output:hdmi-stereo-extra2+input:analog-stereo` (`Sortie Digital Stereo (HDMI 3) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 5765
DEBUG        + Card profile added: `output:hdmi-surround-extra2` (`Sortie Digital Surround 5.1 (HDMI 3)`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround-extra2+input:analog-stereo` (`Sortie Digital Surround 5.1 (HDMI 3) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 665
DEBUG        + Card profile added: `output:hdmi-surround71-extra2` (`Sortie Digital Surround 7.1 (HDMI 3)`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround71-extra2+input:analog-stereo` (`Sortie Digital Surround 7.1 (HDMI 3) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 665
DEBUG        + Card profile added: `output:hdmi-stereo-extra3` (`Sortie Digital Stereo (HDMI 4)`), 1 sinks, 0 sources, priority: 5700
DEBUG        + Card profile added: `output:hdmi-stereo-extra3+input:analog-stereo` (`Sortie Digital Stereo (HDMI 4) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 5765
DEBUG        + Card profile added: `output:hdmi-surround-extra3` (`Sortie Digital Surround 5.1 (HDMI 4)`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround-extra3+input:analog-stereo` (`Sortie Digital Surround 5.1 (HDMI 4) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 665
DEBUG        + Card profile added: `output:hdmi-surround71-extra3` (`Sortie Digital Surround 7.1 (HDMI 4)`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround71-extra3+input:analog-stereo` (`Sortie Digital Surround 7.1 (HDMI 4) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 665
DEBUG        + Card profile added: `output:hdmi-stereo-extra4` (`Sortie Digital Stereo (HDMI 5)`), 1 sinks, 0 sources, priority: 5700
DEBUG        + Card profile added: `output:hdmi-stereo-extra4+input:analog-stereo` (`Sortie Digital Stereo (HDMI 5) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 5765
DEBUG        + Card profile added: `output:hdmi-surround-extra4` (`Sortie Digital Surround 5.1 (HDMI 5)`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround-extra4+input:analog-stereo` (`Sortie Digital Surround 5.1 (HDMI 5) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 665
DEBUG        + Card profile added: `output:hdmi-surround71-extra4` (`Sortie Digital Surround 7.1 (HDMI 5)`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround71-extra4+input:analog-stereo` (`Sortie Digital Surround 7.1 (HDMI 5) + Entrée Stéréo analogique`), 1 sinks, 1 sources, priority: 665
DEBUG        + Card profile added: `off` (`Éteint`), 0 sinks, 0 sources, priority: 0
DEBUG        + Card port added: `analog-input-internal-mic` (`Microphone interne`); priority: 8900; direction: 2; available: Yes
DEBUG          . Supported profile: `input:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo-extra1+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo-extra2+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround-extra2+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71-extra2+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo-extra3+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround-extra3+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71-extra3+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo-extra4+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround-extra4+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71-extra4+input:analog-stereo`
DEBUG        + Card port added: `analog-input-headset-mic` (`Microphone casque`); priority: 8800; direction: 2; available: No
DEBUG          . Supported profile: `input:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo-extra1+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo-extra2+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround-extra2+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71-extra2+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo-extra3+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround-extra3+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71-extra3+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo-extra4+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround-extra4+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71-extra4+input:analog-stereo`
DEBUG        + Card port added: `analog-output-speaker` (`Haut-parleurs`); priority: 10000; direction: 1; available: Yes
DEBUG          . Supported profile: `output:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
DEBUG        + Card port added: `analog-output-headphones` (`Casque audio`); priority: 9900; direction: 1; available: No
DEBUG          . Supported profile: `output:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
DEBUG        + Card port added: `hdmi-output-0` (`HDMI / DisplayPort`); priority: 5900; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo`
DEBUG          . Supported profile: `output:hdmi-stereo+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround`
DEBUG          . Supported profile: `output:hdmi-surround+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71`
DEBUG          . Supported profile: `output:hdmi-surround71+input:analog-stereo`
DEBUG        + Card port added: `hdmi-output-1` (`HDMI / DisplayPort 2`); priority: 5800; direction: 1; available: Yes
DEBUG          . Supported profile: `output:hdmi-stereo-extra1`
DEBUG          . Supported profile: `output:hdmi-stereo-extra1+input:analog-stereo`
DEBUG        + Card port added: `hdmi-output-2` (`HDMI / DisplayPort 3`); priority: 5700; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo-extra2`
DEBUG          . Supported profile: `output:hdmi-stereo-extra2+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround-extra2`
DEBUG          . Supported profile: `output:hdmi-surround-extra2+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71-extra2`
DEBUG          . Supported profile: `output:hdmi-surround71-extra2+input:analog-stereo`
DEBUG        + Card port added: `hdmi-output-3` (`HDMI / DisplayPort 4`); priority: 5600; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo-extra3`
DEBUG          . Supported profile: `output:hdmi-stereo-extra3+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround-extra3`
DEBUG          . Supported profile: `output:hdmi-surround-extra3+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71-extra3`
DEBUG          . Supported profile: `output:hdmi-surround71-extra3+input:analog-stereo`
DEBUG        + Card port added: `hdmi-output-4` (`HDMI / DisplayPort 5`); priority: 5500; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo-extra4`
DEBUG          . Supported profile: `output:hdmi-stereo-extra4+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround-extra4`
DEBUG          . Supported profile: `output:hdmi-surround-extra4+input:analog-stereo`
DEBUG          . Supported profile: `output:hdmi-surround71-extra4`
DEBUG          . Supported profile: `output:hdmi-surround71-extra4+input:analog-stereo`
DEBUG    .menu_insert_ordered_item(): inserting item `    Audio interne ‣ Microphone interne` at index 1
DEBUG    .menu_insert_ordered_item(): inserting item `    Audio interne ‣ Microphone casque` at index 1 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    Audio interne ‣ Haut-parleurs` at index 7
DEBUG    .menu_insert_ordered_item(): inserting item `    Audio interne ‣ Casque audio` at index 7 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    Audio interne ‣ HDMI / DisplayPort` at index 8 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    Audio interne ‣ HDMI / DisplayPort 2` at index 9
DEBUG    .menu_insert_ordered_item(): inserting item `    Audio interne ‣ HDMI / DisplayPort 3` at index 10 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    Audio interne ‣ HDMI / DisplayPort 4` at index 11 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    Audio interne ‣ HDMI / DisplayPort 5` at index 12 (hidden)
DEBUG      + Card[3] added: `alsa_card.usb-JBL_Quantum_400_0079CM-0059338GK-00`, driver: `module-alsa-card.c`
DEBUG        + Card profile added: `output:analog-stereo` (`Sortie Stéréo analogique`), 1 sinks, 0 sources, priority: 6500 -- Active
DEBUG        + Card profile added: `output:iec958-stereo` (`Sortie Stéréo numérique (IEC958)`), 1 sinks, 0 sources, priority: 5500
DEBUG        + Card profile added: `off` (`Éteint`), 0 sinks, 0 sources, priority: 0
DEBUG        + Card port added: `analog-output` (`Sortie analogique`); priority: 9900; direction: 1; available: Yes
DEBUG          . Supported profile: `output:analog-stereo`
DEBUG        + Card port added: `iec958-stereo-output` (`Sortie numérique (S/PDIF)`); priority: 0; direction: 1; available: Yes
DEBUG          . Supported profile: `output:iec958-stereo`
DEBUG    .menu_insert_ordered_item(): inserting item `    Quantum 400 ‣ Sortie analogique` at index 14
DEBUG    .menu_insert_ordered_item(): inserting item `    Quantum 400 ‣ Sortie numérique (S/PDIF)` at index 15
DEBUG      + Source[1] added: `alsa_input.usb-0c76_USB_PnP_Audio_Device-00.mono-fallback`, card 0
DEBUG        + Source port added: `analog-input-mic` (`Microphone`); priority: 8700; available: Yes
DEBUG        * Activated source port `analog-input-mic`
DEBUG      + Source[3] added: `alsa_input.pci-0000_00_1f.3.analog-stereo`, card 1
DEBUG        + Source port added: `analog-input-internal-mic` (`Microphone interne`); priority: 8900; available: Yes
DEBUG        + Source port added: `analog-input-headset-mic` (`Microphone casque`); priority: 8800; available: No
DEBUG        * Activated source port `analog-input-headset-mic`
DEBUG      + Sink[0] added: `alsa_output.usb-0c76_USB_PnP_Audio_Device-00.analog-stereo`, card 0
DEBUG        + Sink port added: `analog-output-speaker` (`Haut-parleurs`); priority: 10000; available: Yes
DEBUG        * Activated sink port `analog-output-speaker`
DEBUG      + Sink[1] added: `alsa_output.pci-0000_00_1f.3.analog-stereo`, card 1
DEBUG        + Sink port added: `analog-output-speaker` (`Haut-parleurs`); priority: 10000; available: Yes
DEBUG        + Sink port added: `analog-output-headphones` (`Casque audio`); priority: 9900; available: No
DEBUG        * Activated sink port `analog-output-headphones`
DEBUG      + Sink[5] added: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        + Sink port added: `analog-output` (`Sortie analogique`); priority: 9900; available: Yes
DEBUG        * Activated sink port `analog-output`
DEBUG    * Activated sink: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`
DEBUG    * Activated source: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo.monitor`
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 52)
DEBUG      + Sink input[52] added: `dialog-information` -> sink 5
DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 53)
DEBUG      + Sink input[53] added: `Playback` -> sink 5
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 53)
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 53)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 52)
DEBUG      - Sink input[52] removed: `dialog-information`
DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 53)
DEBUG      - Sink input[53] removed: `Playback`
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 54)
DEBUG      + Sink input[54] added: `dialog-information` -> sink 5
DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 55)
DEBUG      + Sink input[55] added: `Playback` -> sink 5
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 55)
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 55)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 54)
DEBUG      - Sink input[54] removed: `dialog-information`
DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 55)
DEBUG      - Sink input[55] removed: `Playback`
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 56)
DEBUG      + Sink input[56] added: `dialog-information` -> sink 5
DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 57)
DEBUG      + Sink input[57] added: `Playback` -> sink 5
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 57)
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 57)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 56)
DEBUG      - Sink input[56] removed: `dialog-information`
DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 57)
DEBUG      - Sink input[57] removed: `Playback`
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 58)
DEBUG      + Sink input[58] added: `Playback` -> sink 5
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 58)
DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 59)
DEBUG      + Sink input[59] added: `dialog-information` -> sink 5
DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 60)
DEBUG      + Sink input[60] added: `Playback` -> sink 5
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 60)
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 58)
DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 59)
DEBUG      - Sink input[59] removed: `dialog-information`
DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 58)
DEBUG      - Sink input[58] removed: `Playback`
DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 60)
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 5)
DEBUG      * Sink[5] updated: `alsa_output.usb-JBL_Quantum_400_0079CM-0059338GK-00.analog-stereo`, card 3
DEBUG        * Activated sink port `analog-output`
DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 7)
DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 60)
DEBUG      - Sink input[60] removed: `Playback`
```

I know that the software keep running in the background -->

```bash
newmax@censured:~/Applications/gtk-4.3.2 $ ps aux | grep -i 'indicator'
newmax      1361  0.0  0.8 792876 68396 ?        Sl   17:47   0:00 /usr/bin/python3 /usr/bin/indicator-sound-switcher
newmax     11011  0.0  0.0  46952  2480 pts/0    S+   19:03   0:00 grep --color=auto -i indicator
```

**Additional context**
I wanted to install ISS to enable my microphone because it's the only software who may work with it

**Comment by yktoo** [comment] 2021-08-19 15:40
Might be related to #91, which hasn't been resolved for the lack of input.

To comment on this:

> When trying without sudo you'll not have any outputs and the app not appear in the system tray or else So it seems that sudo mode isn't great for this software but it would work without.

You shouldn't start the SSI as root. It won't have access to either PulseAudio or your desktop, as both are run under your user account.

**Comment by bambury** [comment] 2021-12-18 18:14
Same here, software running but no tray icon. It only happened recently, so probably the (Cinnamon?) update that causes this just reached me.

**Comment by yktoo** [comment] 2021-12-19 15:00
I mark this as a duplicate of #91.

I have just pushed version 2.3.7 of the app, with fallback PNG/SVG icons. Please give it a try and report back if the problem persists.

**Closed by yktoo** 2021-12-19 15:00 UTC
Labels: bug
