### ISSUE TITLE
Remember connected bluetooth devices and automatically reconnect

### ISSUE THREAD

**Issue by eoghanmurray** [yktoo/indicator-sound-switcher#33] opened 2016-09-30 09:23 UTC
Hi yktoo,

Thanks for a great widget!

I use it to switch between my headphones and my external bluetooth speakers.
However, most of the time when I open the dropdown menu, the bluetooth speakers are not listed. I have to go into the bluetooth menu, go to the submenu for my device, and change the connection from 'Off' to 'On'.

So my feature request is for indicator-sound-switcher to remember previous bluetooth devices and list them even when they are not connected and then handle turning on the bluetooth connection as needed.
If the bluetooth device isn't in range then I guess this would have to be indicated beside it's name in the list.

I take it that this would be a big change as it would involve delving into bluetooth details instead of soundcard-related details, but it would make a big impact for me usability wise.

Thanks for the work so far and feel free to close this issue if it is too far out of scope.

Eoghan

**Comment by mishagale** [comment] 2016-10-16 11:56
@eoghanmurray I seem to have essentially the same issue, but I don't think it's really something @yktoo can fix in this applet - the problem is that the Bluetooth software doesn't automatically reconnect paired device. However, you might look at [this AskUbuntu thread](http://askubuntu.com/questions/8409/autoconnecting-bluetooth-devices) - you'll still have to manually enable the Bluetooth connection, but you can configure PulseAudio to automatically switch to the Bluetooth audio device

**Comment by yktoo** [comment] 2016-10-31 17:41
As @mishagale pointed out it's indeed a problem that involves messing with the Bluetooth stack, which would really be a big side step. I think in your particular use case the link he provided offers a viable alternative; otherwise I would actually expect that Bluetooth and PulseAudio dudes make necessary improvements to the relevant subsystems. Closing for now.

**Closed by yktoo** 2016-10-31 17:41 UTC
Labels: wontfix
