### ISSUE TITLE
Does not load properly on Cinnamon Startup

### ISSUE THREAD

**Issue by PreciousWarrior** [yktoo/indicator-sound-switcher#92] opened 2020-08-24 12:16 UTC
**Describe the bug**
The applet icon does not load properly during startup, and a notification pops up saying-: Cinnamon loaded successfully, but one or more applets, desklets or extensions failed to load during startup. Contact the developer to solve this issue. The menu still loads when clicked, and all the options in the menu work as intended, but the quit option does not seem to do anything.

**To Reproduce**
1. Make sure the indicator-sound-switcher application is open
2. Reboot your PC or shut it down and turn it on again
3. See error in notifications and applet icon missing in tray

**Expected behavior**
The applet icon should load properly, the quit option should work as intended, and I should not be notified of any error by Cinnamon.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Desktop environment: Cinnamon 4.6.7
 - Sound Switcher Indicator version: 2.3.4

**Indicator log:**
No output. I quit the program using resource monitor (since the quit button does not work), and ran the commands in the terminal, and there was no output.

**Comment by geeks-r-us** [comment] 2020-12-24 15:27
OS Ubuntu 20.10 Cinnamon flavor 
Desktop: Cinnamon 4.6.7
Sound Switcher Indicator 2.3.4-1

Not sure which of the packages recently updated but today the Sound Switch Indicator is back in the traybar but without icon.
It shows up with a blank field in the traybar

**Comment by yktoo** [comment] 2020-12-28 16:35
Can't reproduce it on a vanilla Mint 20 Cinnamon install, with all upgrades installed.
![image](https://user-images.githubusercontent.com/1675911/103229219-edb22680-4932-11eb-9765-e848c9e1a487.png)

System:
![image](https://user-images.githubusercontent.com/1675911/103229304-133f3000-4933-11eb-8344-7292708daf65.png)

Used SSI version 2.3.5.2.

**Comment by yktoo** [comment] 2021-06-18 13:05
Closing until more info is available.

**Closed by yktoo** 2021-06-18 13:05 UTC
Labels: bug
