### ISSUE TITLE
[BUG] System tray icon missing in Qtile

### ISSUE THREAD

**Issue by mcizek-2** [yktoo/indicator-sound-switcher#115] opened 2022-01-29 16:14 UTC
When using the application with my Qtile window manager, the system tray icon is missing. It might be a problem with Qtile, because it seems to work in other WMs. Still here is the output of indicator-sound-switcher -vv

```(indicator-sound-switcher:7507): Gtk-WARNING **: 11:25:51.681: Theme parsing error: gtk.css:5760:26: '-shadow' is not a valid color name

(indicator-sound-switcher:7507): Gtk-WARNING **: 11:25:51.681: Theme parsing error: gtk.css:5763:14: not a number

(indicator-sound-switcher:7507): Gtk-WARNING **: 11:25:51.681: Theme parsing error: gtk.css:5764:13: not a number

(indicator-sound-switcher:7507): Gtk-WARNING **: 11:25:51.681: Theme parsing error: gtk.css:5765:11: Expected a length
INFO     Starting indicator application
INFO     Loaded configuration file /home/keen/.config/indicator-sound-switcher.json
DEBUG    KeyboardManager.bind_keys()
DEBUG    .menu_append_item(): appending item `Inputs`
DEBUG    .menu_append_item(): appending separator
DEBUG    .menu_append_item(): appending item `Outputs`
DEBUG    .menu_append_item(): appending separator
DEBUG    .menu_append_item(): appending item `_Refresh`
DEBUG    .menu_append_item(): appending item `_Preferences…`
DEBUG    .menu_append_item(): appending item `_About`
DEBUG    .menu_append_item(): appending item `_Quit`
DEBUG    Trying to connect to PulseAudio daemon, attempt #1
INFO     Context connected
DEBUG      + Card[0] added: `alsa_card.pci-0000_01_00.1`, driver: `module-alsa-card.c`
DEBUG        + Card profile added: `output:hdmi-stereo` (`Digital Stereo (HDMI) Output`), 1 sinks, 0 sources, priority: 5900
DEBUG        + Card profile added: `output:hdmi-surround` (`Digital Surround 5.1 (HDMI) Output`), 1 sinks, 0 sources, priority: 800
DEBUG        + Card profile added: `output:hdmi-surround71` (`Digital Surround 7.1 (HDMI) Output`), 1 sinks, 0 sources, priority: 800
DEBUG        + Card profile added: `output:hdmi-stereo-extra1` (`Digital Stereo (HDMI 2) Output`), 1 sinks, 0 sources, priority: 38468 -- Active
DEBUG        + Card profile added: `output:hdmi-stereo-extra2` (`Digital Stereo (HDMI 3) Output`), 1 sinks, 0 sources, priority: 5700
DEBUG        + Card profile added: `output:hdmi-surround-extra2` (`Digital Surround 5.1 (HDMI 3) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround71-extra2` (`Digital Surround 7.1 (HDMI 3) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-stereo-extra3` (`Digital Stereo (HDMI 4) Output`), 1 sinks, 0 sources, priority: 5700
DEBUG        + Card profile added: `output:hdmi-surround-extra3` (`Digital Surround 5.1 (HDMI 4) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround71-extra3` (`Digital Surround 7.1 (HDMI 4) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-stereo-extra4` (`Digital Stereo (HDMI 5) Output`), 1 sinks, 0 sources, priority: 5700
DEBUG        + Card profile added: `output:hdmi-surround-extra4` (`Digital Surround 5.1 (HDMI 5) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround71-extra4` (`Digital Surround 7.1 (HDMI 5) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-stereo-extra5` (`Digital Stereo (HDMI 6) Output`), 1 sinks, 0 sources, priority: 5700
DEBUG        + Card profile added: `output:hdmi-surround-extra5` (`Digital Surround 5.1 (HDMI 6) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround71-extra5` (`Digital Surround 7.1 (HDMI 6) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-stereo-extra6` (`Digital Stereo (HDMI 7) Output`), 1 sinks, 0 sources, priority: 5700
DEBUG        + Card profile added: `output:hdmi-surround-extra6` (`Digital Surround 5.1 (HDMI 7) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `output:hdmi-surround71-extra6` (`Digital Surround 7.1 (HDMI 7) Output`), 1 sinks, 0 sources, priority: 600
DEBUG        + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEBUG        + Card port added: `hdmi-output-0` (`HDMI / DisplayPort`); priority: 5900; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo`
DEBUG          . Supported profile: `output:hdmi-surround`
DEBUG          . Supported profile: `output:hdmi-surround71`
DEBUG        + Card port added: `hdmi-output-1` (`HDMI / DisplayPort 2`); priority: 5800; direction: 1; available: Yes
DEBUG          . Supported profile: `output:hdmi-stereo-extra1`
DEBUG        + Card port added: `hdmi-output-2` (`HDMI / DisplayPort 3`); priority: 5700; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo-extra2`
DEBUG          . Supported profile: `output:hdmi-surround-extra2`
DEBUG          . Supported profile: `output:hdmi-surround71-extra2`
DEBUG        + Card port added: `hdmi-output-3` (`HDMI / DisplayPort 4`); priority: 5600; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo-extra3`
DEBUG          . Supported profile: `output:hdmi-surround-extra3`
DEBUG          . Supported profile: `output:hdmi-surround71-extra3`
DEBUG        + Card port added: `hdmi-output-4` (`HDMI / DisplayPort 5`); priority: 5500; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo-extra4`
DEBUG          . Supported profile: `output:hdmi-surround-extra4`
DEBUG          . Supported profile: `output:hdmi-surround71-extra4`
DEBUG        + Card port added: `hdmi-output-5` (`HDMI / DisplayPort 6`); priority: 5400; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo-extra5`
DEBUG          . Supported profile: `output:hdmi-surround-extra5`
DEBUG          . Supported profile: `output:hdmi-surround71-extra5`
DEBUG        + Card port added: `hdmi-output-6` (`HDMI / DisplayPort 7`); priority: 5300; direction: 1; available: No
DEBUG          . Supported profile: `output:hdmi-stereo-extra6`
DEBUG          . Supported profile: `output:hdmi-surround-extra6`
DEBUG          . Supported profile: `output:hdmi-surround71-extra6`
DEBUG    .menu_insert_ordered_item(): inserting item `    TU104 HD Audio Controller ‣ HDMI / DisplayPort` at index 3 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    TU104 HD Audio Controller ‣ HDMI / DisplayPort 2` at index 4
DEBUG    .menu_insert_ordered_item(): inserting item `    TU104 HD Audio Controller ‣ HDMI / DisplayPort 3` at index 5 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    TU104 HD Audio Controller ‣ HDMI / DisplayPort 4` at index 6 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    TU104 HD Audio Controller ‣ HDMI / DisplayPort 5` at index 7 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    TU104 HD Audio Controller ‣ HDMI / DisplayPort 6` at index 8 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    TU104 HD Audio Controller ‣ HDMI / DisplayPort 7` at index 9 (hidden)
DEBUG      + Card[1] added: `alsa_card.usb-Razer_Razer_Nari_Essential-00`, driver: `module-alsa-card.c`
DEBUG        + Card profile added: `input:mono-fallback` (`Mono Input`), 0 sinks, 1 sources, priority: 1
DEBUG        + Card profile added: `output:analog-stereo` (`Analog Stereo Output`), 1 sinks, 0 sources, priority: 6500
DEBUG        + Card profile added: `output:analog-stereo+input:mono-fallback` (`Analog Stereo Output + Mono Input`), 1 sinks, 1 sources, priority: 6501
DEBUG        + Card profile added: `output:iec958-stereo` (`Digital Stereo (IEC958) Output`), 1 sinks, 0 sources, priority: 5500 -- Active
DEBUG        + Card profile added: `output:iec958-stereo+input:mono-fallback` (`Digital Stereo (IEC958) Output + Mono Input`), 1 sinks, 1 sources, priority: 5501
DEBUG        + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEBUG        + Card port added: `analog-input-mic` (`Microphone`); priority: 8700; direction: 2; available: Yes
DEBUG          . Supported profile: `input:mono-fallback`
DEBUG          . Supported profile: `output:analog-stereo+input:mono-fallback`
DEBUG          . Supported profile: `output:iec958-stereo+input:mono-fallback`
DEBUG        + Card port added: `analog-output` (`Analog Output`); priority: 9900; direction: 1; available: Yes
DEBUG          . Supported profile: `output:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:mono-fallback`
DEBUG        + Card port added: `iec958-stereo-output` (`Digital Output (S/PDIF)`); priority: 0; direction: 1; available: Yes
DEBUG          . Supported profile: `output:iec958-stereo`
DEBUG          . Supported profile: `output:iec958-stereo+input:mono-fallback`
DEBUG    .menu_insert_ordered_item(): inserting item `    RC30-026902, Gaming Headset [Nari Essential, Wireless, Receiver] ‣ Microphone` at index 1
DEBUG    .menu_insert_ordered_item(): inserting item `    RC30-026902, Gaming Headset [Nari Essential, Wireless, Receiver] ‣ Analog Output` at index 4
DEBUG    .menu_insert_ordered_item(): inserting item `    RC30-026902, Gaming Headset [Nari Essential, Wireless, Receiver] ‣ Digital Output (S/PDIF)` at index 5
DEBUG      + Card[2] added: `alsa_card.usb-Sunplus_IT_Co_Live_Streamer_CAM_313_20190816001-02`, driver: `module-alsa-card.c`
DEBUG        + Card profile added: `input:mono-fallback` (`Mono Input`), 0 sinks, 1 sources, priority: 1 -- Active
DEBUG        + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEBUG        + Card port added: `analog-input-mic` (`Microphone`); priority: 8700; direction: 2; available: Yes
DEBUG          . Supported profile: `input:mono-fallback`
DEBUG    .menu_insert_ordered_item(): inserting item `    Live Streamer CAM 313 ‣ Microphone` at index 1
DEBUG      + Card[3] added: `alsa_card.pci-0000_00_1b.0`, driver: `module-alsa-card.c`
DEBUG        + Card profile added: `input:analog-stereo` (`Analog Stereo Input`), 0 sinks, 1 sources, priority: 65
DEBUG        + Card profile added: `output:analog-stereo` (`Analog Stereo Output`), 1 sinks, 0 sources, priority: 39268 -- Active
DEBUG        + Card profile added: `output:analog-stereo+input:analog-stereo` (`Analog Stereo Duplex`), 1 sinks, 1 sources, priority: 6565
DEBUG        + Card profile added: `output:analog-surround-21` (`Analog Surround 2.1 Output`), 1 sinks, 0 sources, priority: 34068
DEBUG        + Card profile added: `output:analog-surround-21+input:analog-stereo` (`Analog Surround 2.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 1365
DEBUG        + Card profile added: `output:analog-surround-40` (`Analog Surround 4.0 Output`), 1 sinks, 0 sources, priority: 33968
DEBUG        + Card profile added: `output:analog-surround-40+input:analog-stereo` (`Analog Surround 4.0 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 1265
DEBUG        + Card profile added: `output:analog-surround-41` (`Analog Surround 4.1 Output`), 1 sinks, 0 sources, priority: 34068
DEBUG        + Card profile added: `output:analog-surround-41+input:analog-stereo` (`Analog Surround 4.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 1365
DEBUG        + Card profile added: `output:analog-surround-50` (`Analog Surround 5.0 Output`), 1 sinks, 0 sources, priority: 33968
DEBUG        + Card profile added: `output:analog-surround-50+input:analog-stereo` (`Analog Surround 5.0 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 1265
DEBUG        + Card profile added: `output:analog-surround-51` (`Analog Surround 5.1 Output`), 1 sinks, 0 sources, priority: 34068
DEBUG        + Card profile added: `output:analog-surround-51+input:analog-stereo` (`Analog Surround 5.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 1365
DEBUG        + Card profile added: `output:analog-surround-71` (`Analog Surround 7.1 Output`), 1 sinks, 0 sources, priority: 33968
DEBUG        + Card profile added: `output:analog-surround-71+input:analog-stereo` (`Analog Surround 7.1 Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 1265
DEBUG        + Card profile added: `output:iec958-stereo` (`Digital Stereo (IEC958) Output`), 1 sinks, 0 sources, priority: 38268
DEBUG        + Card profile added: `output:iec958-stereo+input:analog-stereo` (`Digital Stereo (IEC958) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5565
DEBUG        + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
DEBUG        + Card port added: `analog-input-front-mic` (`Front Microphone`); priority: 8500; direction: 2; available: No
DEBUG          . Supported profile: `input:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEBUG          . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEBUG        + Card port added: `analog-input-rear-mic` (`Rear Microphone`); priority: 8200; direction: 2; available: No
DEBUG          . Supported profile: `input:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEBUG          . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEBUG        + Card port added: `analog-input-linein` (`Line In`); priority: 8100; direction: 2; available: No
DEBUG          . Supported profile: `input:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEBUG          . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEBUG        + Card port added: `analog-output-lineout` (`Line Out`); priority: 9000; direction: 1; available: Yes
DEBUG          . Supported profile: `output:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-21`
DEBUG          . Supported profile: `output:analog-surround-21+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-40`
DEBUG          . Supported profile: `output:analog-surround-40+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-41`
DEBUG          . Supported profile: `output:analog-surround-41+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-50`
DEBUG          . Supported profile: `output:analog-surround-50+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-51`
DEBUG          . Supported profile: `output:analog-surround-51+input:analog-stereo`
DEBUG          . Supported profile: `output:analog-surround-71`
DEBUG          . Supported profile: `output:analog-surround-71+input:analog-stereo`
DEBUG        + Card port added: `analog-output-headphones` (`Headphones`); priority: 9900; direction: 1; available: No
DEBUG          . Supported profile: `output:analog-stereo`
DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
DEBUG        + Card port added: `iec958-stereo-output` (`Digital Output (S/PDIF)`); priority: 0; direction: 1; available: Yes
DEBUG          . Supported profile: `output:iec958-stereo`
DEBUG          . Supported profile: `output:iec958-stereo+input:analog-stereo`
DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Front Microphone` at index 1 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Rear Microphone` at index 2 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Line In` at index 2 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Line Out` at index 8
DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Headphones` at index 8 (hidden)
DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Digital Output (S/PDIF)` at index 8
DEBUG      + Source[2] added: `alsa_input.usb-Sunplus_IT_Co_Live_Streamer_CAM_313_20190816001-02.mono-fallback`, card 2
DEBUG        + Source port added: `analog-input-mic` (`Microphone`); priority: 8700; available: Yes
DEBUG        * Activated source port `analog-input-mic`
DEBUG      + Sink[1] added: `alsa_output.usb-Razer_Razer_Nari_Essential-00.iec958-stereo`, card 1
DEBUG        + Sink port added: `iec958-stereo-output` (`Digital Output (S/PDIF)`); priority: 0; available: Yes
DEBUG        * Activated sink port `iec958-stereo-output`
DEBUG      + Sink[2] added: `alsa_output.pci-0000_00_1b.0.analog-stereo`, card 3
DEBUG        + Sink port added: `analog-output-lineout` (`Line Out`); priority: 9000; available: Yes
DEBUG        + Sink port added: `analog-output-headphones` (`Headphones`); priority: 9900; available: No
DEBUG        * Activated sink port `analog-output-lineout`
DEBUG      + Sink[4] added: `alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1`, card 0
DEBUG        + Sink port added: `hdmi-output-1` (`HDMI / DisplayPort 2`); priority: 5800; available: Yes
DEBUG        * Activated sink port `hdmi-output-1`
DEBUG    * Activated sink: `alsa_output.usb-Razer_Razer_Nari_Essential-00.iec958-stereo`
DEBUG    * Activated source: `alsa_input.usb-Sunplus_IT_Co_Live_Streamer_CAM_313_20190816001-02.mono-fallback`

(indicator-sound-switcher:7507): Gdk-CRITICAL **: 11:25:51.980: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Traceback (most recent call last):
  File "/usr/bin/indicator-sound-switcher", line 33, in <module>
    sys.exit(load_entry_point('indicator-sound-switcher==2.3.7', 'console_scripts', 'indicator-sound-switcher')())
  File "/usr/lib/python3.9/site-packages/indicator_sound_switcher/__init__.py", line 66, in main
    SoundSwitcherIndicator().run()
  File "/usr/lib/python3.9/site-packages/indicator_sound_switcher/indicator.py", line 949, in run
    Gtk.main()
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 1680, in main
    return _Gtk_main(*args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/lib/python3.9/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt
```

I think the issue is with 
```bash
(indicator-sound-switcher:7507): Gdk-CRITICAL **: 11:25:51.980: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

I don't know much about how gtk works, so I'd appreciate any help with this, thanks a lot.

**Comment by yktoo** [comment] 2022-01-30 08:04
Well I guess it's indeed caused by the window manager, and this doesn't seem something that can be resolved in the app. You may try swapping the indicator library used (`AppIndicator3` ⇔ `AyatanaAppIndicator3`).

**Comment by madhur** [comment] 2022-02-05 15:37
Happens with me too on Cinnamon 4.6.2. The app is working but the icon is blank

**Comment by yktoo** [comment] 2022-02-07 16:28
@madhur Can't reproduce it (stock Ubuntu Cinnamon 20.04.3):
![image](https://user-images.githubusercontent.com/1675911/152829568-7a939cd4-4329-49bc-82a8-ac9e9bd6c422.png)

**Comment by madhur** [comment] 2022-02-08 04:28
@yktoo Can you try installing with snap. I believe it happens when app is installed with snap

**Comment by yktoo** [comment] 2022-02-08 18:35
After a few experiments I can conclude that the problem is apparently in Cinnamon's tray implementation or something of that sort.

* I tried swapping `libayatana-appindicator3-1` for `libappindicator3-1` in the snap package, with an even worse result: there was no menu at all in Ubuntu Cinnamon.
* In stock Ubuntu 20.04, on the contrary, both versions of the snap worked perfectly.

Why exactly that happens is too deep to dig for me, but most likely a fix from DE and/or library developers is required.

For the time being you'll need to resort to using a `.deb` I'm afraid.

**Closed by yktoo** 2022-02-08 18:35 UTC
Labels: bug

**Comment by mcizek-2** [comment] 2022-02-08 21:55
> @mcizek-2 Did you also install SSI from snap?
I'm on Gentoo, so I actually compiled it, but I have a same problem on Ubuntu after installing it with apt. It just seems like a problem with the Qtile tray.
