### ISSUE TITLE
Add support for switching device profiles

### ISSUE THREAD

**Issue by hotice** [yktoo/indicator-sound-switcher#3] opened 2014-02-03 16:11 UTC
On each system restart, Indicator Sound Switcher displays just the HDMI output, even if I select "Refresh device list". This only happens after a system restart (a simple logout doesn't trigger this behaviour).

If I open System Settings > Sound and switch the output to something else, Indicator Sound Switcher then correctly displays the output sources (headphones and speakers show up in the list).

Tested under Ubuntu 14.04 with Sound Switcher Indicator 1.2.0.

**Comment by tdu-audio** [comment] 2016-05-17 16:18
We don't know where we should be starting, but since this seemed like the most appropriate thread, we'll drop some questions. Further details will be ready upon requests.

Basically, we are having some issues while using RME FireFace UFX (in USB Class-Compliant Mode). Because we need 22ch output with one of the ADAT disabled for SPDIF, maintaining the output of the device operating in `Altset 2` (as shown in `cat /proc/asound/card1/stream0`) is a must.

After finding out that changing profiles in _indicator\-sound_ was doing the trick, we then wanted to know ways for enabling multichannel-input and multichannel-output. 

```
Playback:
	Status: Stop
	Interface 1
		Altset 1
		Format: S24_3LE
		Channels: 2
		Endpoint: 1 OUT (ASYNC)
		Rates: 44100, 48000, 88200, 96000, 176400, 192000
		Data packet interval: 125 us
	Interface 1
		Altset 2
		Format: S24_3LE
		Channels: 22
		Endpoint: 1 OUT (ASYNC)
		Rates: 44100, 48000, 88200, 96000, 176400, 192000
		Data packet interval: 125 us

Capture:
	Status: Stop
	Interface 2
		Altset 1
		Format: S24_3LE
		Channels: 22
		Endpoint: 2 IN (ASYNC)
		Rates: 44100, 48000, 88200, 96000, 176400, 192000
		Data packet interval: 125 us
	Interface 2
		Altset 2
		Format: S24_3LE
		Channels: 12
		Endpoint: 2 IN (ASYNC)
		Rates: 44100, 48000, 88200, 96000, 176400, 192000
		Data packet interval: 125 us
```

Because the host runs _jackd_ normally for audio playback (and then _PulseAudio Jack Sink_ is in effect), this is not really a problem for us - we see all 22ch when running _jackd_. The problem is, we now want to use _Octave_ to enable the use of _mataa_ for some audio analysis. For technical reasons, we have decided that _jackd_ should be stopped while using _mataa_. 
The issue begins when we start talking about setting Output-9, Output-10, Input-9 and Input-10 of UFX as the default device to the system, as to be defined in `/etc/asound.conf`.

Sorry for a non-descriptive comment, but I hope you'll ask me for detailed descriptions of the situation as needed.

Thanks in advance.

**Comment by yktoo** [comment] 2016-09-25 15:38
Must be fixed in 2.0.1.

**Closed by yktoo** 2016-09-25 15:38 UTC
Labels: enhancement

**Comment by repsa** [comment] 2016-09-26 08:57
Hi everyone, i'have implemented profiles in my fork,  so temporary, you can use it:
https://github.com/repsa/indicator-sound-switcher

**Comment by nifr** [comment] 2016-09-26 14:39
@yktoo thanks for your efforts - you just made my day *switches to bluetooth headset* :sunglasses:
