### ISSUE TITLE
[BUG] PulseEffects creates 2 entries in the SoundSwitcher menu that can not be removed

### ISSUE THREAD

**Issue by hustlebwnz** [yktoo/indicator-sound-switcher#104] opened 2021-01-30 09:29 UTC
After installing PulseEffects on Ubuntu, 2 outputs appear; PulseEffects(app) and PulseEffects(mic). They do not appear in the preferences menu to hide, and do not appear in the config file.

 - OS: Ubuntu 20.04.2
 - Desktop environment: Gnome 3.36.8
 - SoundSwitcher version 2.3.5.2

running the indicator returns these relevant lines:
DEBUG    .menu_insert_ordered_item(): inserting item `    PulseEffects(apps)` at index 11
DEBUG      + Sink[5] added: `PulseEffects_mic`, card 4294967295
DEBUG    .menu_insert_ordered_item(): inserting item `    PulseEffects(mic)` at index 12

**Comment by yktoo** [comment] 2021-06-18 14:13
I believe it's a duplicate of #68.

**Closed by yktoo** 2021-06-18 14:13 UTC
Labels: bug, duplicate
