### ISSUE TITLE
Add keyboard shortcut

### ISSUE THREAD

**Issue by paulo-marcondes** [yktoo/indicator-sound-switcher#50] opened 2017-04-05 13:21 UTC
It's an amazing project, but I really miss something like an option to change between two pre-selected outputs using a keyboard shortcut. Using Windows, I can do it using Default Audio Changer.

Thanks!

**Comment by yktoo** [comment] 2017-04-05 13:35
Duplicate of #38, check the solution proposed there.

**Closed by yktoo** 2017-04-05 13:35 UTC
Labels: wontfix
