### ISSUE TITLE
Issue with two outputs from SteelSeries Arctis 7

### ISSUE THREAD

**Issue by yoruvo** [yktoo/indicator-sound-switcher#93] opened 2020-10-02 10:45 UTC
Hello,

thank you for this nifty little tool.

Unfortunately I have an issue using it with the SteelSeries Arctis 7 wireless headset. It has two outputs: One stereo and one mono. However, selecting any of them in the Switcher indicator will use the mono output. Even hiding the mono output in the switcher indictator's settings does not affect this. The mono output will always be the one used, even if the indicator drop-down menu shows that the Stereo output is selected.

![image](https://user-images.githubusercontent.com/48255300/94915361-0f734d00-04ad-11eb-9ce0-523c211e361e.png)

Please let me know if you need further information.

Thanks,
yoruvo

**Comment by yktoo** [comment] 2020-10-04 18:21
This seems to be PulseAudio or ALSA issue. Is it possible to switch to the desired output using another tool, like Gnome Settings or `pavucontrol`? Does profile selection affect the result?

**Comment by yoruvo** [comment] 2020-10-05 22:44
Hi,

thanks for your response. Apologies for not providing more detail of my platform.

The platform is Ubuntu 20.04, running the default theme. 

It is possible to switch the audio device with the regular Sound settings in Ubuntu.

Additionally, this indicator works fine as well: https://extensions.gnome.org/extension/906/sound-output-device-chooser/

**Comment by yktoo** [comment] 2020-10-06 06:46
Interesting. I'll need the output of:

```bash
indicator-sound-switcher -vv
```

That, also after you click a menu item.

**Comment by yoruvo** [comment] 2020-10-20 08:54
Here are the logs with some commentary.

So, initial position is: I'm using "Headphones (SteelSeries Arctis 7)" as output, which is the stereo output, and the SteelSeries Arctis 7 mic as input.

Now I launch the indicator.

> ~> indicator-sound-switcher -vv
> INFO     Starting indicator application
> INFO     Loaded configuration file /home/ivi/.config/indicator-sound-switcher.json
> DEBUG    KeyboardManager.bind_keys()
> DEBUG    .menu_append_item(): appending item `Inputs`
> DEBUG    .menu_append_item(): appending separator
> DEBUG    .menu_append_item(): appending item `Outputs`
> DEBUG    .menu_append_item(): appending separator
> DEBUG    .menu_append_item(): appending item `_Refresh`
> DEBUG    .menu_append_item(): appending item `_Preferences…`
> DEBUG    .menu_append_item(): appending item `_About`
> DEBUG    .menu_append_item(): appending item `_Quit`
> DEBUG    Trying to connect to PulseAudio daemon, attempt #1
> INFO     Context connected
> DEBUG      + Card[0] added: `alsa_card.pci-0000_00_1f.3`, driver: `module-alsa-card.c`
> DEBUG        + Card profile added: `input:analog-stereo` (`Analog Stereo Input`), 0 sinks, 1 sources, priority: 65
> DEBUG        + Card profile added: `output:analog-stereo` (`Analog Stereo Output`), 1 sinks, 0 sources, priority: 6500
> DEBUG        + Card profile added: `output:analog-stereo+input:analog-stereo` (`Analog Stereo Duplex`), 1 sinks, 1 sources, priority: 6565 -- Active
> DEBUG        + Card profile added: `output:hdmi-stereo` (`Digital Stereo (HDMI) Output`), 1 sinks, 0 sources, priority: 5900
> DEBUG        + Card profile added: `output:hdmi-stereo+input:analog-stereo` (`Digital Stereo (HDMI) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5965
> DEBUG        + Card profile added: `output:hdmi-stereo-extra1` (`Digital Stereo (HDMI 2) Output`), 1 sinks, 0 sources, priority: 5700
> DEBUG        + Card profile added: `output:hdmi-stereo-extra1+input:analog-stereo` (`Digital Stereo (HDMI 2) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5765
> DEBUG        + Card profile added: `output:hdmi-surround-extra1` (`Digital Surround 5.1 (HDMI 2) Output`), 1 sinks, 0 sources, priority: 600
> DEBUG        + Card profile added: `output:hdmi-surround-extra1+input:analog-stereo` (`Digital Surround 5.1 (HDMI 2) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 665
> DEBUG        + Card profile added: `output:hdmi-surround71-extra1` (`Digital Surround 7.1 (HDMI 2) Output`), 1 sinks, 0 sources, priority: 600
> DEBUG        + Card profile added: `output:hdmi-surround71-extra1+input:analog-stereo` (`Digital Surround 7.1 (HDMI 2) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 665
> DEBUG        + Card profile added: `output:hdmi-stereo-extra2` (`Digital Stereo (HDMI 3) Output`), 1 sinks, 0 sources, priority: 5700
> DEBUG        + Card profile added: `output:hdmi-stereo-extra2+input:analog-stereo` (`Digital Stereo (HDMI 3) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5765
> DEBUG        + Card profile added: `output:hdmi-surround-extra2` (`Digital Surround 5.1 (HDMI 3) Output`), 1 sinks, 0 sources, priority: 600
> DEBUG        + Card profile added: `output:hdmi-surround-extra2+input:analog-stereo` (`Digital Surround 5.1 (HDMI 3) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 665
> DEBUG        + Card profile added: `output:hdmi-surround71-extra2` (`Digital Surround 7.1 (HDMI 3) Output`), 1 sinks, 0 sources, priority: 600
> DEBUG        + Card profile added: `output:hdmi-surround71-extra2+input:analog-stereo` (`Digital Surround 7.1 (HDMI 3) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 665
> DEBUG        + Card profile added: `output:hdmi-stereo-extra3` (`Digital Stereo (HDMI 4) Output`), 1 sinks, 0 sources, priority: 5700
> DEBUG        + Card profile added: `output:hdmi-stereo-extra3+input:analog-stereo` (`Digital Stereo (HDMI 4) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5765
> DEBUG        + Card profile added: `output:hdmi-surround-extra3` (`Digital Surround 5.1 (HDMI 4) Output`), 1 sinks, 0 sources, priority: 600
> DEBUG        + Card profile added: `output:hdmi-surround-extra3+input:analog-stereo` (`Digital Surround 5.1 (HDMI 4) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 665
> DEBUG        + Card profile added: `output:hdmi-surround71-extra3` (`Digital Surround 7.1 (HDMI 4) Output`), 1 sinks, 0 sources, priority: 600
> DEBUG        + Card profile added: `output:hdmi-surround71-extra3+input:analog-stereo` (`Digital Surround 7.1 (HDMI 4) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 665
> DEBUG        + Card profile added: `output:hdmi-stereo-extra4` (`Digital Stereo (HDMI 5) Output`), 1 sinks, 0 sources, priority: 5700
> DEBUG        + Card profile added: `output:hdmi-stereo-extra4+input:analog-stereo` (`Digital Stereo (HDMI 5) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 5765
> DEBUG        + Card profile added: `output:hdmi-surround-extra4` (`Digital Surround 5.1 (HDMI 5) Output`), 1 sinks, 0 sources, priority: 600
> DEBUG        + Card profile added: `output:hdmi-surround-extra4+input:analog-stereo` (`Digital Surround 5.1 (HDMI 5) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 665
> DEBUG        + Card profile added: `output:hdmi-surround71-extra4` (`Digital Surround 7.1 (HDMI 5) Output`), 1 sinks, 0 sources, priority: 600
> DEBUG        + Card profile added: `output:hdmi-surround71-extra4+input:analog-stereo` (`Digital Surround 7.1 (HDMI 5) Output + Analog Stereo Input`), 1 sinks, 1 sources, priority: 665
> DEBUG        + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
> DEBUG        + Card port added: `analog-input-internal-mic` (`Internal Microphone`); priority: 8900; direction: 2; available: Yes
> DEBUG          . Supported profile: `input:analog-stereo`
> DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra4+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra4+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra4+input:analog-stereo`
> DEBUG        + Card port added: `analog-input-headphone-mic` (`Microphone`); priority: 8700; direction: 2; available: No
> DEBUG          . Supported profile: `input:analog-stereo`
> DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra4+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra4+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra4+input:analog-stereo`
> DEBUG        + Card port added: `analog-input-headset-mic` (`Headset Microphone`); priority: 8800; direction: 2; available: No
> DEBUG          . Supported profile: `input:analog-stereo`
> DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra4+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra4+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra4+input:analog-stereo`
> DEBUG        + Card port added: `analog-output-speaker` (`Speakers`); priority: 10000; direction: 1; available: Yes
> DEBUG          . Supported profile: `output:analog-stereo`
> DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
> DEBUG        + Card port added: `analog-output-headphones` (`Headphones`); priority: 9900; direction: 1; available: No
> DEBUG          . Supported profile: `output:analog-stereo`
> DEBUG          . Supported profile: `output:analog-stereo+input:analog-stereo`
> DEBUG        + Card port added: `hdmi-output-0` (`HDMI / DisplayPort`); priority: 5900; direction: 1; available: Yes
> DEBUG          . Supported profile: `output:hdmi-stereo`
> DEBUG          . Supported profile: `output:hdmi-stereo+input:analog-stereo`
> DEBUG        + Card port added: `hdmi-output-1` (`HDMI / DisplayPort 2`); priority: 5800; direction: 1; available: No
> DEBUG          . Supported profile: `output:hdmi-stereo-extra1`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra1`
> DEBUG          . Supported profile: `output:hdmi-surround-extra1+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra1`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra1+input:analog-stereo`
> DEBUG        + Card port added: `hdmi-output-2` (`HDMI / DisplayPort 3`); priority: 5700; direction: 1; available: No
> DEBUG          . Supported profile: `output:hdmi-stereo-extra2`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra2`
> DEBUG          . Supported profile: `output:hdmi-surround-extra2+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra2`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra2+input:analog-stereo`
> DEBUG        + Card port added: `hdmi-output-3` (`HDMI / DisplayPort 4`); priority: 5600; direction: 1; available: No
> DEBUG          . Supported profile: `output:hdmi-stereo-extra3`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra3`
> DEBUG          . Supported profile: `output:hdmi-surround-extra3+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra3`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra3+input:analog-stereo`
> DEBUG        + Card port added: `hdmi-output-4` (`HDMI / DisplayPort 5`); priority: 5500; direction: 1; available: No
> DEBUG          . Supported profile: `output:hdmi-stereo-extra4`
> DEBUG          . Supported profile: `output:hdmi-stereo-extra4+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround-extra4`
> DEBUG          . Supported profile: `output:hdmi-surround-extra4+input:analog-stereo`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra4`
> DEBUG          . Supported profile: `output:hdmi-surround71-extra4+input:analog-stereo`
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Internal Microphone` at index 1
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Microphone` at index 2 (hidden)
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Headset Microphone` at index 1 (hidden)
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Speakers` at index 6
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ Headphones` at index 6 (hidden)
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ HDMI / DisplayPort` at index 6
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ HDMI / DisplayPort 2` at index 7 (hidden)
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ HDMI / DisplayPort 3` at index 8 (hidden)
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ HDMI / DisplayPort 4` at index 9 (hidden)
> DEBUG    .menu_insert_ordered_item(): inserting item `    Built-in Audio ‣ HDMI / DisplayPort 5` at index 10 (hidden)
> DEBUG      + Card[1] added: `alsa_card.usb-046d_0825_AE416FE0-02`, driver: `module-alsa-card.c`
> DEBUG        + Card profile added: `input:mono-fallback` (`Mono Input`), 0 sinks, 1 sources, priority: 1 -- Active
> DEBUG        + Card profile added: `input:multichannel-input` (`Multichannel Input`), 0 sinks, 1 sources, priority: 1
> DEBUG        + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
> DEBUG        + Card port added: `analog-input-mic` (`Microphone`); priority: 8700; direction: 2; available: Yes
> DEBUG          . Supported profile: `input:mono-fallback`
> DEBUG        + Card port added: `multichannel-input` (`Multichannel Input`); priority: 0; direction: 2; available: Yes
> DEBUG          . Supported profile: `input:multichannel-input`
> DEBUG    .menu_insert_ordered_item(): inserting item `    Webcam C270 ‣ Microphone` at index 4
> DEBUG    .menu_insert_ordered_item(): inserting item `    Webcam C270 ‣ Multichannel Input` at index 5
> DEBUG      + Card[2] added: `alsa_card.usb-SteelSeries_SteelSeries_Arctis_7-00`, driver: `module-alsa-card.c`
> DEBUG        + Card profile added: `output:analog-mono+output:analog-stereo+input:analog-mono` (`Analog Mono Output + Analog Stereo Output + Analog Mono Input`), 2 sinks, 1 sources, priority: 5100 -- Active
> DEBUG        + Card profile added: `input:analog-mono` (`Analog Mono Input`), 0 sinks, 1 sources, priority: 1
> DEBUG        + Card profile added: `output:analog-mono` (`Analog Mono Output`), 1 sinks, 0 sources, priority: 1
> DEBUG        + Card profile added: `output:analog-mono+input:analog-mono` (`Analog Mono Duplex`), 1 sinks, 1 sources, priority: 1
> DEBUG        + Card profile added: `output:analog-stereo` (`Analog Stereo Output`), 1 sinks, 0 sources, priority: 5000
> DEBUG        + Card profile added: `output:analog-stereo+input:analog-mono` (`Analog Stereo Output + Analog Mono Input`), 1 sinks, 1 sources, priority: 5000
> DEBUG        + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
> DEBUG        + Card port added: `usb-gaming-headset-output-mono` (`Headphones Mono Output`); priority: 0; direction: 1; available: Yes
> DEBUG          . Supported profile: `output:analog-mono+output:analog-stereo+input:analog-mono`
> DEBUG          . Supported profile: `output:analog-mono`
> DEBUG          . Supported profile: `output:analog-mono+input:analog-mono`
> DEBUG        + Card port added: `usb-gaming-headset-output-stereo` (`Headphones`); priority: 0; direction: 1; available: Yes
> DEBUG          . Supported profile: `output:analog-mono+output:analog-stereo+input:analog-mono`
> DEBUG          . Supported profile: `output:analog-stereo`
> DEBUG          . Supported profile: `output:analog-stereo+input:analog-mono`
> DEBUG        + Card port added: `usb-gaming-headset-input` (`Headset Microphone`); priority: 0; direction: 2; available: Yes
> DEBUG          . Supported profile: `output:analog-mono+output:analog-stereo+input:analog-mono`
> DEBUG          . Supported profile: `input:analog-mono`
> DEBUG          . Supported profile: `output:analog-mono+input:analog-mono`
> DEBUG          . Supported profile: `output:analog-stereo+input:analog-mono`
> DEBUG    .menu_insert_ordered_item(): inserting item `    SteelSeries Arctis 7 ‣ Headphones Mono Output` at index 15
> DEBUG    .menu_insert_ordered_item(): inserting item `    SteelSeries Arctis 7 ‣ Headphones` at index 15
> DEBUG    .menu_insert_ordered_item(): inserting item `    SteelSeries Arctis 7 ‣ Headset Microphone` at index 4
> DEBUG      + Card[3] added: `alsa_card.usb-Generic_USB_Audio_200901010001-00`, driver: `module-alsa-card.c`
> DEBUG        + Card profile added: `HiFi` (`Default`), 2 sinks, 1 sources, priority: 8000 -- Active
> DEBUG        + Card profile added: `off` (`Off`), 0 sinks, 0 sources, priority: 0
> DEBUG        + Card port added: `[Out] Line` (`Line Out`); priority: 200; direction: 1; available: Yes
> DEBUG          . Supported profile: `HiFi`
> DEBUG        + Card port added: `[Out] Headphones` (`Headphones`); priority: 100; direction: 1; available: Yes
> DEBUG          . Supported profile: `HiFi`
> DEBUG        + Card port added: `[In] Mic` (`Microphone`); priority: 100; direction: 2; available: Yes
> DEBUG          . Supported profile: `HiFi`
> DEBUG      + Source[2] added: `alsa_input.pci-0000_00_1f.3.analog-stereo`, card 0
> DEBUG        + Source port added: `analog-input-internal-mic` (`Internal Microphone`); priority: 8900; available: Yes
> DEBUG        + Source port added: `analog-input-headphone-mic` (`Microphone`); priority: 8700; available: No
> DEBUG        + Source port added: `analog-input-headset-mic` (`Headset Microphone`); priority: 8800; available: No
> DEBUG        * Activated source port `analog-input-internal-mic`
> DEBUG      + Source[3] added: `alsa_input.usb-046d_0825_AE416FE0-02.mono-fallback`, card 1
> DEBUG        + Source port added: `analog-input-mic` (`Microphone`); priority: 8700; available: Yes
> DEBUG        * Activated source port `analog-input-mic`
> DEBUG      + Source[6] added: `alsa_input.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-mono`, card 2
> DEBUG        + Source port added: `usb-gaming-headset-input` (`Headset Microphone`); priority: 0; available: Yes
> DEBUG        * Activated source port `usb-gaming-headset-input`
> DEBUG      + Source[9] added: `alsa_input.usb-Generic_USB_Audio_200901010001-00.HiFi__hw_Dock__source`, card 3
> DEBUG        + Source port added: `[In] Mic` (`Microphone`); priority: 100; available: Yes
> DEBUG        * Activated source port `[In] Mic`
> DEBUG      + Source output[0] added: `Input`
> DEBUG      + Sink[1] added: `alsa_output.pci-0000_00_1f.3.analog-stereo`, card 0
> DEBUG        + Sink port added: `analog-output-speaker` (`Speakers`); priority: 10000; available: Yes
> DEBUG        + Sink port added: `analog-output-headphones` (`Headphones`); priority: 9900; available: No
> DEBUG        * Activated sink port `analog-output-speaker`
> DEBUG      + Sink[2] added: `alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-mono`, card 2
> DEBUG        + Sink port added: `usb-gaming-headset-output-mono` (`Headphones Mono Output`); priority: 0; available: Yes
> DEBUG        * Activated sink port `usb-gaming-headset-output-mono`
> DEBUG      + Sink[3] added: `alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-stereo`, card 2
> DEBUG        + Sink port added: `usb-gaming-headset-output-stereo` (`Headphones`); priority: 0; available: Yes
> DEBUG        * Activated sink port `usb-gaming-headset-output-stereo`
> DEBUG      + Sink[4] added: `alsa_output.usb-Generic_USB_Audio_200901010001-00.HiFi__hw_Dock_1__sink`, card 3
> DEBUG        + Sink port added: `[Out] Line` (`Line Out`); priority: 200; available: Yes
> DEBUG        * Activated sink port `[Out] Line`
> DEBUG      + Sink[5] added: `alsa_output.usb-Generic_USB_Audio_200901010001-00.HiFi__hw_Dock__sink`, card 3
> DEBUG        + Sink port added: `[Out] Headphones` (`Headphones`); priority: 100; available: Yes
> DEBUG        * Activated sink port `[Out] Headphones`
> DEBUG      + Sink input[6] added: `Output` -> sink 3
> DEBUG      + Sink input[13] added: `Spotify` -> sink 3
> DEBUG    * Activated sink: `alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-stereo`
> DEBUG    * Activated source: `alsa_input.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-mono`

The indicator shows:

![image](https://user-images.githubusercontent.com/48255300/96563304-162dfc80-12c2-11eb-98ef-363117316e61.png)

Having clicked the indicator (without changing any settings) added the following logs:

> DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 22)
> DEBUG      + Sink input[22] added: `Playback` -> sink 3
> DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 22)
> DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 22)
> DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 22)
> DEBUG      - Sink input[22] removed: `Playback`
> DEBUG    .do_context_subscribe(facility: 2, kind: 0, index: 23)
> DEBUG      + Sink input[23] added: `Playback` -> sink 3
> DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 23)
> DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 23)
> DEBUG    .do_context_subscribe(facility: 2, kind: 32, index: 23)
> DEBUG      - Sink input[23] removed: `Playback`
> DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 13)
> DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 3)
> DEBUG      * Sink[3] updated: `alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-stereo`, card 2
> DEBUG        * Activated sink port `usb-gaming-headset-output-stereo`
> DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 3)
> DEBUG      * Sink[3] updated: `alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-stereo`, card 2
> DEBUG        * Activated sink port `usb-gaming-headset-output-stereo`
> DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 13)

Now I will click the "Stereo" Arctis output in the indicator.

My sound turns mono, and the following logs appear:

> INFO     # Card[2], port `usb-gaming-headset-output-stereo` selected
> DEBUG    * Switching card[2] to profile `output:analog-mono+output:analog-stereo+input:analog-mono` with priority 5100
> DEBUG    .do_context_subscribe(facility: 7, kind: 16, index: 4294967295)
> DEBUG    * Activated sink: `alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-mono`
> DEBUG    * Activated source: `alsa_input.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-mono`
> DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 6)
> DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 3)
> DEBUG      * Sink[3] updated: `alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-stereo`, card 2
> DEBUG        * Activated sink port `usb-gaming-headset-output-stereo`
> DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 2)
> DEBUG      * Sink[2] updated: `alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-mono`, card 2
> DEBUG        * Activated sink port `usb-gaming-headset-output-mono`
> DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 4)
> DEBUG    .do_context_subscribe(facility: 2, kind: 16, index: 13)
> DEBUG    .do_context_subscribe(facility: 0, kind: 16, index: 3)
> DEBUG      * Sink[3] updated: `alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.analog-stereo`, card 2
> DEBUG        * Activated sink port `usb-gaming-headset-output-stereo`
> DEBUG    .do_context_subscribe(facility: 1, kind: 16, index: 5)

The indicator now shows that Mono is selected, after I picked Stereo:

![image](https://user-images.githubusercontent.com/48255300/96563683-850b5580-12c2-11eb-93bf-a495e54ee1ff.png)

Concurrent attempts to try to click Stereo in the indicator again just post the following lines:

> INFO     # Card[2], port `usb-gaming-headset-output-stereo` selected
> DEBUG    * Switching card[2] to profile `output:analog-mono+output:analog-stereo+input:analog-mono` with priority 5100

**Comment by yktoo** [comment] 2022-05-13 17:22
Looks like a duplicate of #107. Please check if it's fixed in 2.3.8.

**Closed by yktoo** 2022-05-13 17:22 UTC
Labels: bug, duplicate
